module.exports = {
    CAR: 'Car',
    O_Auth: 'O_Auth',
    USER: 'User',
    LESSON: 'Lesson',
    LESSON_T: 'lesson',
    LESSON2_T: 'lesson2',
    TEST_COLUMN: 'test-column',
    RATING: 'Rating',
    RATINGS_T: 'ratings',
    RATINGS2_T: 'ratings2',
    CHARTS2_T: 'charts2',
    GRAPHS2_T: 'graphs2',
    STUDENT: 'Student',
    STUDENTS_T: 'students',
    STUDENTS2_T: 'students2',
    AGE: 'age',
    YEAR_OF_BORN: 'yearOfBorn',
    YEARS_OLD: 'yearsOld',
};
